<?php
/**
 * Provide a public-facing view for the plugin
 *
 * This file is used to markup the public-facing aspects of the plugin.
 *
 * @link       https://me.rgou.net
 * @since      1.0.0
 *
 * @package    Rgou_Wp_Media
 * @subpackage Rgou_Wp_Media/public/partials
 */

$rgou_wp_media_values = get_option( 'rgou_wp_media', false );
if ( $rgou_wp_media_values && isset( $rgou_wp_media_values['timestamp'] ) && $rgou_wp_media_values['timestamp'] ) : ?>
	<p style="text-align:center">
		<a href="<?php esc_url( get_site_url() ); ?>/sitemap.html" target="_blank">Sitemap</a>
		generated by <a href="https://github.com/rafaelgou/rgou-wp-media" target="_blank">RGOU Sitemap</a>
	</p>
	<?php
endif;
